import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import CircularProgress from '@mui/material/CircularProgress';
import { PrimeReactProvider } from "primereact/api";
import BootstrapClient from "@components/BootstrapClient";
import Header from "@components/header/Header";
import { Footer } from "@components/Footer";
import { BackToTop } from "@components/BackToTop";
import styles from "./page.module.css";
import "./globals.css";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider value={{ ripple: true }}>
          <Header />
          <Suspense fallback={<div className={styles.searchLoading}><CircularProgress color="inherit" size={50}/></div>}>
            <main>{children}</main>
            <BackToTop />
            <Footer />
          </Suspense>
        </PrimeReactProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
