import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from "./components/BootstrapClient";
import Header from "./components/header/Header";
import { Footer } from "./components/Footer";
import { BackToTop } from "./components/BackToTop";
import { Loading } from "./components/Loading";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PrimeReactProvider value={{ ripple: true }}>
          <Header />
          <Suspense fallback={<Loading />}>
            <main>{children}</main>
            <BackToTop />
            <Footer />
          </Suspense>
        </PrimeReactProvider>
        <BootstrapClient />
      </body>
    </html>
  );
}
